///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoDesktopApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The clickSubmit recording.
    /// </summary>
    [TestModule("f55c4a1d-e3e7-4548-99c7-01a583216e8b", ModuleType.Recording, 1)]
    public partial class clickSubmit : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoDesktopAppRepository repository.
        /// </summary>
        public static DemoDesktopAppRepository repo = DemoDesktopAppRepository.Instance;

        static clickSubmit instance = new clickSubmit();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public clickSubmit()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static clickSubmit Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.BtnAddPerson' at 37;15.", repo.RxMainFrame.RxTabStandard1.BtnAddPersonInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard1.BtnAddPerson.Click("37;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Success, "User", "Submit Button Selected Successfully", new RecordItemIndex(1));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
