///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DemoDesktopApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DemoDesktopAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("77b7a982-ea7e-4439-a156-85c98fe1f5fb")]
    public partial class DemoDesktopAppRepository : RepoGenBaseFolder
    {
        static DemoDesktopAppRepository instance = new DemoDesktopAppRepository();
        DemoDesktopAppRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        DemoDesktopAppRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the DemoDesktopAppRepository element repository.
        /// </summary>
        [RepositoryFolder("77b7a982-ea7e-4439-a156-85c98fe1f5fb")]
        public static DemoDesktopAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DemoDesktopAppRepository() 
            : base("DemoDesktopAppRepository", "/", null, 0, false, "77b7a982-ea7e-4439-a156-85c98fe1f5fb", ".\\RepositoryImages\\DemoDesktopAppRepository77b7a982.rximgres")
        {
            _rxmainframe = new DemoDesktopAppRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new DemoDesktopAppRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

        string _txtGender = "rdbFemale";

        /// <summary>
        /// Gets or sets the value of variable txtGender.
        /// </summary>
        [TestVariable("579622b2-73b6-43ef-9875-4e8e15b41601")]
        public string txtGender
        {
            get { return _txtGender; }
            set { _txtGender = value; }
        }

        string _txtSelectDepartment = "Management";

        /// <summary>
        /// Gets or sets the value of variable txtSelectDepartment.
        /// </summary>
        [TestVariable("01bf2a27-35e2-4e1c-96f3-943e371728ff")]
        public string txtSelectDepartment
        {
            get { return _txtSelectDepartment; }
            set { _txtSelectDepartment = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("77b7a982-ea7e-4439-a156-85c98fe1f5fb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("f32931bc-fbd2-4000-8101-e91cb6e0222f")]
        public virtual DemoDesktopAppRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("600532e0-3460-4f78-b665-00a8381e8176")]
        public virtual DemoDesktopAppRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DemoDesktopAppRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("f32931bc-fbd2-4000-8101-e91cb6e0222f")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            DemoDesktopAppRepositoryFolders.RxTabStandard1Folder _rxtabstandard1;
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "f32931bc-fbd2-4000-8101-e91cb6e0222f", "")
            {
                _rxtabstandard1 = new DemoDesktopAppRepositoryFolders.RxTabStandard1Folder(this);
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "b2e3c897-5bcd-495e-8fe8-ce165a548f17");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "9daa6610-1805-4a16-a288-9207a71618ec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f32931bc-fbd2-4000-8101-e91cb6e0222f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f32931bc-fbd2-4000-8101-e91cb6e0222f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("b2e3c897-5bcd-495e-8fe8-ce165a548f17")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("b2e3c897-5bcd-495e-8fe8-ce165a548f17")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("9daa6610-1805-4a16-a288-9207a71618ec")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("9daa6610-1805-4a16-a288-9207a71618ec")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard1 folder.
            /// </summary>
            [RepositoryFolder("1db34e45-08ef-4f35-a7e8-1141c8d76091")]
            public virtual DemoDesktopAppRepositoryFolders.RxTabStandard1Folder RxTabStandard1
            {
                get { return _rxtabstandard1; }
            }
        }

        /// <summary>
        /// The RxTabStandard1Folder folder.
        /// </summary>
        [RepositoryFolder("1db34e45-08ef-4f35-a7e8-1141c8d76091")]
        public partial class RxTabStandard1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _rxtabstandardInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbgenderInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _buttonupInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;

            /// <summary>
            /// Creates a new RxTabStandard1  folder.
            /// </summary>
            public RxTabStandard1Folder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard1", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "1db34e45-08ef-4f35-a7e8-1141c8d76091", "")
            {
                _rxtabstandardInfo = new RepoItemInfo(this, "RxTabStandard", "", 30000, null, "0ba7a9b1-8359-4c83-8498-5f4d4d139b8b");
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", 30000, null, "a70bf0f5-3c53-4f7d-812f-a412cf6c3b8f");
                _rdbgenderInfo = new RepoItemInfo(this, "RdbGender", "?/?/radiobutton[@controlname=$txtGender]", 30000, null, "425d71c5-f99e-4794-8e0b-dbebba3d216c");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", 30000, null, "e7f62847-284e-4ca1-b17e-b80ee5c80ef4");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "button[@controlname='btnAddPerson']", 30000, null, "e42dd469-41df-4335-adae-11fed0a707ef");
                _buttonupInfo = new RepoItemInfo(this, "ButtonUp", "container[@controlname='txtAge']/?/?/button[@accessiblename='Up']", 30000, null, "be91b53f-d02c-4e61-a9d3-405636a7324e");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "text[@controlname='lblNumberOfPersonsNumber']", 30000, null, "d9f560e4-98d2-4942-82c6-51ad530ce5e0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1db34e45-08ef-4f35-a7e8-1141c8d76091")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1db34e45-08ef-4f35-a7e8-1141c8d76091")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard item.
            /// </summary>
            [RepositoryItem("0ba7a9b1-8359-4c83-8498-5f4d4d139b8b")]
            public virtual Ranorex.TabPage RxTabStandard
            {
                get
                {
                    return _rxtabstandardInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The RxTabStandard item info.
            /// </summary>
            [RepositoryItemInfo("0ba7a9b1-8359-4c83-8498-5f4d4d139b8b")]
            public virtual RepoItemInfo RxTabStandardInfo
            {
                get
                {
                    return _rxtabstandardInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("a70bf0f5-3c53-4f7d-812f-a412cf6c3b8f")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("a70bf0f5-3c53-4f7d-812f-a412cf6c3b8f")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbGender item.
            /// </summary>
            [RepositoryItem("425d71c5-f99e-4794-8e0b-dbebba3d216c")]
            public virtual Ranorex.RadioButton RdbGender
            {
                get
                {
                    return _rdbgenderInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbGender item info.
            /// </summary>
            [RepositoryItemInfo("425d71c5-f99e-4794-8e0b-dbebba3d216c")]
            public virtual RepoItemInfo RdbGenderInfo
            {
                get
                {
                    return _rdbgenderInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("e7f62847-284e-4ca1-b17e-b80ee5c80ef4")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("e7f62847-284e-4ca1-b17e-b80ee5c80ef4")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("e42dd469-41df-4335-adae-11fed0a707ef")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("e42dd469-41df-4335-adae-11fed0a707ef")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The ButtonUp item.
            /// </summary>
            [RepositoryItem("be91b53f-d02c-4e61-a9d3-405636a7324e")]
            public virtual Ranorex.Button ButtonUp
            {
                get
                {
                    return _buttonupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonUp item info.
            /// </summary>
            [RepositoryItemInfo("be91b53f-d02c-4e61-a9d3-405636a7324e")]
            public virtual RepoItemInfo ButtonUpInfo
            {
                get
                {
                    return _buttonupInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("d9f560e4-98d2-4942-82c6-51ad530ce5e0")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("d9f560e4-98d2-4942-82c6-51ad530ce5e0")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("600532e0-3460-4f78-b665-00a8381e8176")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selectdepartmentInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "600532e0-3460-4f78-b665-00a8381e8176", "")
            {
                _selectdepartmentInfo = new RepoItemInfo(this, "SelectDepartment", "listitem[@text=$txtSelectDepartment]", 30000, null, "eb87158f-dbd9-4bdf-9a76-99828127be86");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("600532e0-3460-4f78-b665-00a8381e8176")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("600532e0-3460-4f78-b665-00a8381e8176")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectDepartment item.
            /// </summary>
            [RepositoryItem("eb87158f-dbd9-4bdf-9a76-99828127be86")]
            public virtual Ranorex.ListItem SelectDepartment
            {
                get
                {
                    return _selectdepartmentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SelectDepartment item info.
            /// </summary>
            [RepositoryItemInfo("eb87158f-dbd9-4bdf-9a76-99828127be86")]
            public virtual RepoItemInfo SelectDepartmentInfo
            {
                get
                {
                    return _selectdepartmentInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
