///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoDesktopApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The insertFirstName recording.
    /// </summary>
    [TestModule("7b332cd7-845d-4aee-b47c-ee641f9d36ae", ModuleType.Recording, 1)]
    public partial class InsertFirstName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoDesktopAppRepository repository.
        /// </summary>
        public static DemoDesktopAppRepository repo = DemoDesktopAppRepository.Instance;

        static InsertFirstName instance = new InsertFirstName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsertFirstName()
        {
            txtFirstName = "ABC";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsertFirstName Instance
        {
            get { return instance; }
        }

#region Variables

        string _txtFirstName;

        /// <summary>
        /// Gets or sets the value of variable txtFirstName.
        /// </summary>
        [TestVariable("cf44dc7d-1fe3-497f-9167-6b81bf6957ae")]
        public string txtFirstName
        {
            get { return _txtFirstName; }
            set { _txtFirstName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.FirstName' at 97;15.", repo.RxMainFrame.RxTabStandard1.FirstNameInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard1.FirstName.Click("97;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$txtFirstName' with focus on 'RxMainFrame.RxTabStandard1.FirstName'.", repo.RxMainFrame.RxTabStandard1.FirstNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard1.FirstName.PressKeys(txtFirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Success, "User", "First Name Entered Successfully", new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
