///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoDesktopApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The insertLastName recording.
    /// </summary>
    [TestModule("b82be79e-3dce-4f38-8b79-b204a518bf01", ModuleType.Recording, 1)]
    public partial class insertLastName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoDesktopAppRepository repository.
        /// </summary>
        public static DemoDesktopAppRepository repo = DemoDesktopAppRepository.Instance;

        static insertLastName instance = new insertLastName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public insertLastName()
        {
            txtLastName = "DEF";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static insertLastName Instance
        {
            get { return instance; }
        }

#region Variables

        string _txtLastName;

        /// <summary>
        /// Gets or sets the value of variable txtLastName.
        /// </summary>
        [TestVariable("41406032-4bb1-401c-b728-d3feaf1dea7e")]
        public string txtLastName
        {
            get { return _txtLastName; }
            set { _txtLastName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.RxTabStandard' at 221;73.", repo.RxMainFrame.RxTabStandard1.RxTabStandardInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard1.RxTabStandard.Click("221;73");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$txtLastName' with focus on 'RxMainFrame'.", repo.RxMainFrame.SelfInfo, new RecordItemIndex(1));
            repo.RxMainFrame.Self.EnsureVisible();
            Keyboard.Press(txtLastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Success, "User", "Last Name Entered Successfully", new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
