///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoDesktopApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The insertAge recording.
    /// </summary>
    [TestModule("6d8641c7-19a7-4d7b-abcd-adfe68112cfc", ModuleType.Recording, 1)]
    public partial class insertAge : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoDesktopAppRepository repository.
        /// </summary>
        public static DemoDesktopAppRepository repo = DemoDesktopAppRepository.Instance;

        static insertAge instance = new insertAge();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public insertAge()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static insertAge Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RxMainFrame.RxTabStandard1.ButtonUp' at 6;5.", repo.RxMainFrame.RxTabStandard1.ButtonUpInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard1.ButtonUp.DoubleClick("6;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RxMainFrame.RxTabStandard1.ButtonUp' at 6;5.", repo.RxMainFrame.RxTabStandard1.ButtonUpInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard1.ButtonUp.DoubleClick("6;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.ButtonUp' at 6;4.", repo.RxMainFrame.RxTabStandard1.ButtonUpInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard1.ButtonUp.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.ButtonUp' at 6;4.", repo.RxMainFrame.RxTabStandard1.ButtonUpInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard1.ButtonUp.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.ButtonUp' at 6;4.", repo.RxMainFrame.RxTabStandard1.ButtonUpInfo, new RecordItemIndex(4));
            repo.RxMainFrame.RxTabStandard1.ButtonUp.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Success, "User", "Age Entered Successfully", new RecordItemIndex(5));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
