///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoDesktopApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RecordingofAddEntry recording.
    /// </summary>
    [TestModule("5d1978cc-4172-4f4b-a772-d67e66ac935e", ModuleType.Recording, 1)]
    public partial class RecordingofAddEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoDesktopAppRepository repository.
        /// </summary>
        public static DemoDesktopAppRepository repo = DemoDesktopAppRepository.Instance;

        static RecordingofAddEntry instance = new RecordingofAddEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RecordingofAddEntry()
        {
            txtFirstName = "ABC";
            txtLastName = "DEF";
            txtExpected = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RecordingofAddEntry Instance
        {
            get { return instance; }
        }

#region Variables

        string _txtFirstName;

        /// <summary>
        /// Gets or sets the value of variable txtFirstName.
        /// </summary>
        [TestVariable("8c16d8f5-f2bb-4811-bc7a-f25f416f36af")]
        public string txtFirstName
        {
            get { return _txtFirstName; }
            set { _txtFirstName = value; }
        }

        string _txtLastName;

        /// <summary>
        /// Gets or sets the value of variable txtLastName.
        /// </summary>
        [TestVariable("4d4eda4e-d22c-47c1-adfb-c95b5bcfd917")]
        public string txtLastName
        {
            get { return _txtLastName; }
            set { _txtLastName = value; }
        }

        string _txtExpected;

        /// <summary>
        /// Gets or sets the value of variable txtExpected.
        /// </summary>
        [TestVariable("a9cb2b6f-d946-4146-9d1e-76efdb28b56e")]
        public string txtExpected
        {
            get { return _txtExpected; }
            set { _txtExpected = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
