///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoDesktopApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("a28b576f-f410-44a2-9d7c-86e468d952ad", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoDesktopAppRepository repository.
        /// </summary>
        public static DemoDesktopAppRepository repo = DemoDesktopAppRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            txtFirstName = "ABC";
            txtLastName = "DEF";
            txtExpected = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _txtFirstName;

        /// <summary>
        /// Gets or sets the value of variable txtFirstName.
        /// </summary>
        [TestVariable("ecc33ac8-5db9-41c7-acd9-0b8436c139cd")]
        public string txtFirstName
        {
            get { return _txtFirstName; }
            set { _txtFirstName = value; }
        }

        string _txtLastName;

        /// <summary>
        /// Gets or sets the value of variable txtLastName.
        /// </summary>
        [TestVariable("ce12bc88-cd54-4c9d-a21f-809cd6f43b2e")]
        public string txtLastName
        {
            get { return _txtLastName; }
            set { _txtLastName = value; }
        }

        string _txtExpected;

        /// <summary>
        /// Gets or sets the value of variable txtExpected.
        /// </summary>
        [TestVariable("e8f8515a-0a64-4898-afdb-c56a791d3a1a")]
        public string txtExpected
        {
            get { return _txtExpected; }
            set { _txtExpected = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable txtSelectDepartment.
        /// </summary>
        [TestVariable("01bf2a27-35e2-4e1c-96f3-943e371728ff")]
        public string txtSelectDepartment
        {
            get { return repo.txtSelectDepartment; }
            set { repo.txtSelectDepartment = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable txtGender.
        /// </summary>
        [TestVariable("579622b2-73b6-43ef-9875-4e8e15b41601")]
        public string txtGender
        {
            get { return repo.txtGender; }
            set { repo.txtGender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.TestDatabase' at 35;4.", repo.RxMainFrame.TestDatabaseInfo, new RecordItemIndex(0));
            repo.RxMainFrame.TestDatabase.Click("35;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.FirstName' at 97;15.", repo.RxMainFrame.RxTabStandard1.FirstNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard1.FirstName.Click("97;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$txtFirstName' with focus on 'RxMainFrame.RxTabStandard1.FirstName'.", repo.RxMainFrame.RxTabStandard1.FirstNameInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard1.FirstName.PressKeys(txtFirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.RxTabStandard' at 221;73.", repo.RxMainFrame.RxTabStandard1.RxTabStandardInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard1.RxTabStandard.Click("221;73");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$txtLastName' with focus on 'RxMainFrame'.", repo.RxMainFrame.SelfInfo, new RecordItemIndex(4));
            repo.RxMainFrame.Self.EnsureVisible();
            Keyboard.Press(txtLastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.Open' at 10;12.", repo.RxMainFrame.RxTabStandard1.OpenInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabStandard1.Open.Click("10;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.SelectDepartment' at 317;3.", repo.List1000.SelectDepartmentInfo, new RecordItemIndex(6));
            repo.List1000.SelectDepartment.Click("317;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RxMainFrame.RxTabStandard1.ButtonUp' at 6;5.", repo.RxMainFrame.RxTabStandard1.ButtonUpInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabStandard1.ButtonUp.DoubleClick("6;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RxMainFrame.RxTabStandard1.ButtonUp' at 6;5.", repo.RxMainFrame.RxTabStandard1.ButtonUpInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabStandard1.ButtonUp.DoubleClick("6;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.ButtonUp' at 6;4.", repo.RxMainFrame.RxTabStandard1.ButtonUpInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabStandard1.ButtonUp.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.ButtonUp' at 6;4.", repo.RxMainFrame.RxTabStandard1.ButtonUpInfo, new RecordItemIndex(10));
            repo.RxMainFrame.RxTabStandard1.ButtonUp.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.ButtonUp' at 6;4.", repo.RxMainFrame.RxTabStandard1.ButtonUpInfo, new RecordItemIndex(11));
            repo.RxMainFrame.RxTabStandard1.ButtonUp.Click("6;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.RdbGender' at 6;11.", repo.RxMainFrame.RxTabStandard1.RdbGenderInfo, new RecordItemIndex(12));
            repo.RxMainFrame.RxTabStandard1.RdbGender.Click("6;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard1.BtnAddPerson' at 37;15.", repo.RxMainFrame.RxTabStandard1.BtnAddPersonInfo, new RecordItemIndex(13));
            repo.RxMainFrame.RxTabStandard1.BtnAddPerson.Click("37;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption=$txtExpected) on item 'RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumber'.", repo.RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumberInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumberInfo, "Caption", txtExpected);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$txtExpected) on item 'RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumber'.", repo.RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumberInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumberInfo, "Text", txtExpected);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
