///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoDesktopApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validateTestCase recording.
    /// </summary>
    [TestModule("b991d13f-b73b-4dc6-b96d-e31790291940", ModuleType.Recording, 1)]
    public partial class validateTestCase : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoDesktopAppRepository repository.
        /// </summary>
        public static DemoDesktopAppRepository repo = DemoDesktopAppRepository.Instance;

        static validateTestCase instance = new validateTestCase();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validateTestCase()
        {
            txtExpected = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validateTestCase Instance
        {
            get { return instance; }
        }

#region Variables

        string _txtExpected;

        /// <summary>
        /// Gets or sets the value of variable txtExpected.
        /// </summary>
        [TestVariable("e4fa29ce-9193-418e-a799-1bc96b2d6277")]
        public string txtExpected
        {
            get { return _txtExpected; }
            set { _txtExpected = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$txtExpected) on item 'RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumber'.", repo.RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumberInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumberInfo, "Text", txtExpected);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption=$txtExpected) on item 'RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumber'.", repo.RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumberInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabStandard1.LblNumberOfPersonsNumberInfo, "Caption", txtExpected);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
